---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
  - name: ubuntu-14.04
  - name: debian-7.0
  - name: fedora-20
  - name: opensuse-12.3

suites:
  - name: default
    run_list:
      - recipe[stow::default]
    attributes:
